env:
  browser: true
  es2021: true
  tampermonkey: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  max-len: off
  no-plusplus: off
  no-restricted-syntax: off
